First-page-mobile-version
maanikandan/Portfolio-mobile pull request #3
Opened 2023-04-27 02:50 UTC by maanikandan

### This PR contains :
-Header
-Content
-Social links

2023-04-27 03:28 UTC, Efiamotu-1 requested changes
Hi @maanikandan , 

![](https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67)

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 03:28 UTC, Efiamotu-1 commented on .DS_Store
- [ ] For your readme file the information used in the `setup`, `usuage` and `deployment` are all the same, please kindly ensure that your provide descriptive messages for each of these sections detailing how users and recruiters are to run and test the projects on their local machine or devices. :+1:

2023-04-27 03:28 UTC, Efiamotu-1 commented on .DS_Store
- [ ] You currently have an inconsistent design from the provided fgma template and i would like you to work on improving this aspect below are the two designs 
> - figma design
![header-portfolio](https://user-images.githubusercontent.com/89055502/234751227-6b6f3c7c-7882-4e30-821e-ac761101691e.png)
>- your design 
![student-3](https://user-images.githubusercontent.com/89055502/234751284-b0d03826-f3a0-4485-a9cb-7c2ce814c3f3.png)

- [ ] from your design you would notice how the paragrah detailing `I can help you build your product` overflows into the background image however this is not the case with the figma design. kindly work on fixing this design flaw as it is essential that your present your webpage just like the figma template. It shows how much attention you pay to details as a developer and this is good when designing front end projects where clients want specific done as designed :+1:

2023-04-28 07:58 UTC, maanikandan commented on .DS_Store
![portfolio](https://user-images.githubusercontent.com/90455433/235089074-b67adee8-a7ee-41b7-bb64-fd02e882fa46.jpeg)

Everything is fine!

2023-04-28 08:17 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @maanikandan 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
- All linter checks are passing ✔
- Descriptive PR title ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:17 UTC, AbelG101 commented on .DS_Store
### THIS COMMENT IS FOR THE README AND DOESN'T APPLY TO THIS FILE
- [ ] Please make sure you provide the proper instructions on your README as this will help people who'd want to use your project to properly set it up and have it running.
- The Deployment section is where you'd mention how to deploy your project to a remote server and I'm seeing you're only mentioning how to run it. So please make sure to fix it.
- You could for example say:
  > `npm run deploy` using gh-pages
  >  Deploy via Netlify CLI or Netlify Git site or any preferred hosting site (following their instructions)

2023-04-28 08:47 UTC, frank1738 approved these changes
Hi @maanikandan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/FT0UFROtAbVEA/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good documentation

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:51 UTC, merged